from BatchLauncher import BatchLauncher,Tree

outputDirectory = "/home/llr/cms/sauvan/DATA/sauvan/L1/Ntuples/EGammaStage2/Neutrino_Pt-2to20_gun/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/"
outputFile = "tree_electron_stage2.root"

mainDirectory = "/grid_mnt/data1__data.polcms/cms/sauvan/L1/Ntuples/electronTrees/Neutrino_Pt-2to20_gun/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/AODSIM/2014_09_09/"

mainFiles = []
mainFiles.append(mainDirectory+"tree_electron_100_1_l9j.root")
mainFiles.append(mainDirectory+"tree_electron_101_1_tGw.root")
mainFiles.append(mainDirectory+"tree_electron_102_1_9hw.root")
mainFiles.append(mainDirectory+"tree_electron_103_1_lLD.root")
mainFiles.append(mainDirectory+"tree_electron_104_1_VyI.root")
mainFiles.append(mainDirectory+"tree_electron_105_1_w8G.root")
mainFiles.append(mainDirectory+"tree_electron_106_1_8KS.root")
mainFiles.append(mainDirectory+"tree_electron_107_1_rOv.root")
mainFiles.append(mainDirectory+"tree_electron_108_1_Cfj.root")
mainFiles.append(mainDirectory+"tree_electron_109_1_QBi.root")
mainFiles.append(mainDirectory+"tree_electron_10_1_4RM.root")
mainFiles.append(mainDirectory+"tree_electron_110_1_Wdu.root")
mainFiles.append(mainDirectory+"tree_electron_111_1_RDV.root")
mainFiles.append(mainDirectory+"tree_electron_112_1_aNi.root")
mainFiles.append(mainDirectory+"tree_electron_113_1_hEi.root")
mainFiles.append(mainDirectory+"tree_electron_114_1_pm5.root")
mainFiles.append(mainDirectory+"tree_electron_115_1_W83.root")
mainFiles.append(mainDirectory+"tree_electron_116_1_XNf.root")
mainFiles.append(mainDirectory+"tree_electron_117_1_7r1.root")
mainFiles.append(mainDirectory+"tree_electron_118_1_dMs.root")
mainFiles.append(mainDirectory+"tree_electron_119_1_Mvu.root")
mainFiles.append(mainDirectory+"tree_electron_11_1_rKV.root")
mainFiles.append(mainDirectory+"tree_electron_120_1_BZB.root")
mainFiles.append(mainDirectory+"tree_electron_121_1_S3h.root")
mainFiles.append(mainDirectory+"tree_electron_122_1_YDX.root")
mainFiles.append(mainDirectory+"tree_electron_123_1_6eq.root")
mainFiles.append(mainDirectory+"tree_electron_124_1_yWM.root")
mainFiles.append(mainDirectory+"tree_electron_125_1_q4K.root")
mainFiles.append(mainDirectory+"tree_electron_126_1_iUV.root")
mainFiles.append(mainDirectory+"tree_electron_127_1_fPv.root")
mainFiles.append(mainDirectory+"tree_electron_128_1_bJS.root")
mainFiles.append(mainDirectory+"tree_electron_129_1_EKm.root")
mainFiles.append(mainDirectory+"tree_electron_12_1_rbv.root")
mainFiles.append(mainDirectory+"tree_electron_130_1_xcf.root")
mainFiles.append(mainDirectory+"tree_electron_131_1_Slr.root")
mainFiles.append(mainDirectory+"tree_electron_132_1_MOQ.root")
mainFiles.append(mainDirectory+"tree_electron_133_1_x4q.root")
mainFiles.append(mainDirectory+"tree_electron_134_1_yRi.root")
mainFiles.append(mainDirectory+"tree_electron_135_1_ETG.root")
mainFiles.append(mainDirectory+"tree_electron_136_1_hLi.root")
mainFiles.append(mainDirectory+"tree_electron_137_1_FYJ.root")
mainFiles.append(mainDirectory+"tree_electron_138_1_krs.root")
mainFiles.append(mainDirectory+"tree_electron_139_1_r9V.root")
mainFiles.append(mainDirectory+"tree_electron_13_1_o8K.root")
mainFiles.append(mainDirectory+"tree_electron_140_1_e3H.root")
mainFiles.append(mainDirectory+"tree_electron_141_1_y7W.root")
mainFiles.append(mainDirectory+"tree_electron_142_1_xvj.root")
mainFiles.append(mainDirectory+"tree_electron_143_1_zoU.root")
mainFiles.append(mainDirectory+"tree_electron_144_1_4ty.root")
mainFiles.append(mainDirectory+"tree_electron_145_1_2tu.root")
mainFiles.append(mainDirectory+"tree_electron_146_1_QS1.root")
mainFiles.append(mainDirectory+"tree_electron_147_1_lAE.root")
mainFiles.append(mainDirectory+"tree_electron_148_1_GsL.root")
mainFiles.append(mainDirectory+"tree_electron_149_1_3bP.root")
mainFiles.append(mainDirectory+"tree_electron_14_1_sR0.root")
mainFiles.append(mainDirectory+"tree_electron_150_1_nnk.root")
mainFiles.append(mainDirectory+"tree_electron_151_1_B2U.root")
mainFiles.append(mainDirectory+"tree_electron_152_1_dnC.root")
mainFiles.append(mainDirectory+"tree_electron_153_1_GR0.root")
mainFiles.append(mainDirectory+"tree_electron_154_1_0iC.root")
mainFiles.append(mainDirectory+"tree_electron_155_1_gVu.root")
mainFiles.append(mainDirectory+"tree_electron_156_1_Gf3.root")
mainFiles.append(mainDirectory+"tree_electron_157_1_mMS.root")
mainFiles.append(mainDirectory+"tree_electron_158_1_7uO.root")
mainFiles.append(mainDirectory+"tree_electron_159_1_WxU.root")
mainFiles.append(mainDirectory+"tree_electron_15_1_Hna.root")
mainFiles.append(mainDirectory+"tree_electron_160_1_p5Q.root")
mainFiles.append(mainDirectory+"tree_electron_161_1_zSF.root")
mainFiles.append(mainDirectory+"tree_electron_162_1_ttB.root")
mainFiles.append(mainDirectory+"tree_electron_163_1_cet.root")
mainFiles.append(mainDirectory+"tree_electron_164_1_F9Y.root")
mainFiles.append(mainDirectory+"tree_electron_165_1_j3O.root")
mainFiles.append(mainDirectory+"tree_electron_166_1_vL6.root")
mainFiles.append(mainDirectory+"tree_electron_167_1_h60.root")
mainFiles.append(mainDirectory+"tree_electron_168_1_3Nn.root")
mainFiles.append(mainDirectory+"tree_electron_169_1_Xly.root")
mainFiles.append(mainDirectory+"tree_electron_16_1_zcA.root")
mainFiles.append(mainDirectory+"tree_electron_170_1_rq2.root")
mainFiles.append(mainDirectory+"tree_electron_171_1_0Ph.root")
mainFiles.append(mainDirectory+"tree_electron_172_1_Fn4.root")
mainFiles.append(mainDirectory+"tree_electron_173_1_40p.root")
mainFiles.append(mainDirectory+"tree_electron_174_1_zQK.root")
mainFiles.append(mainDirectory+"tree_electron_175_1_Fn6.root")
mainFiles.append(mainDirectory+"tree_electron_176_1_Hpz.root")
mainFiles.append(mainDirectory+"tree_electron_177_1_nTL.root")
mainFiles.append(mainDirectory+"tree_electron_178_1_jY5.root")
mainFiles.append(mainDirectory+"tree_electron_179_1_34h.root")
mainFiles.append(mainDirectory+"tree_electron_17_1_VQD.root")
mainFiles.append(mainDirectory+"tree_electron_180_1_IWf.root")
mainFiles.append(mainDirectory+"tree_electron_181_1_aAC.root")
mainFiles.append(mainDirectory+"tree_electron_182_1_VPN.root")
mainFiles.append(mainDirectory+"tree_electron_183_1_DuS.root")
mainFiles.append(mainDirectory+"tree_electron_184_1_3te.root")
mainFiles.append(mainDirectory+"tree_electron_185_1_ZYi.root")
mainFiles.append(mainDirectory+"tree_electron_186_1_6bi.root")
mainFiles.append(mainDirectory+"tree_electron_187_1_9mP.root")
mainFiles.append(mainDirectory+"tree_electron_188_1_Lk2.root")
mainFiles.append(mainDirectory+"tree_electron_189_1_Kv2.root")
mainFiles.append(mainDirectory+"tree_electron_18_1_7qq.root")
mainFiles.append(mainDirectory+"tree_electron_190_1_89W.root")
mainFiles.append(mainDirectory+"tree_electron_191_1_lj3.root")
mainFiles.append(mainDirectory+"tree_electron_192_1_ixh.root")
mainFiles.append(mainDirectory+"tree_electron_193_1_eF6.root")
mainFiles.append(mainDirectory+"tree_electron_194_1_YHy.root")
mainFiles.append(mainDirectory+"tree_electron_195_1_9ZX.root")
mainFiles.append(mainDirectory+"tree_electron_196_1_1o3.root")
mainFiles.append(mainDirectory+"tree_electron_197_1_cPI.root")
mainFiles.append(mainDirectory+"tree_electron_198_1_aDE.root")
mainFiles.append(mainDirectory+"tree_electron_199_1_uxp.root")
mainFiles.append(mainDirectory+"tree_electron_19_1_KlI.root")
mainFiles.append(mainDirectory+"tree_electron_1_1_Wpz.root")
mainFiles.append(mainDirectory+"tree_electron_200_1_1Ee.root")
mainFiles.append(mainDirectory+"tree_electron_201_1_U3o.root")
mainFiles.append(mainDirectory+"tree_electron_202_1_zDl.root")
mainFiles.append(mainDirectory+"tree_electron_203_1_rwZ.root")
mainFiles.append(mainDirectory+"tree_electron_204_1_3WW.root")
mainFiles.append(mainDirectory+"tree_electron_205_1_2FF.root")
mainFiles.append(mainDirectory+"tree_electron_206_1_qDi.root")
mainFiles.append(mainDirectory+"tree_electron_207_1_7QO.root")
mainFiles.append(mainDirectory+"tree_electron_208_1_evX.root")
mainFiles.append(mainDirectory+"tree_electron_209_1_3dY.root")
mainFiles.append(mainDirectory+"tree_electron_20_1_Qj2.root")
mainFiles.append(mainDirectory+"tree_electron_210_1_6aI.root")
mainFiles.append(mainDirectory+"tree_electron_211_1_EEl.root")
mainFiles.append(mainDirectory+"tree_electron_212_1_2F5.root")
mainFiles.append(mainDirectory+"tree_electron_213_1_8gn.root")
mainFiles.append(mainDirectory+"tree_electron_214_1_sF9.root")
mainFiles.append(mainDirectory+"tree_electron_215_1_HEM.root")
mainFiles.append(mainDirectory+"tree_electron_216_1_gGE.root")
mainFiles.append(mainDirectory+"tree_electron_217_1_usI.root")
mainFiles.append(mainDirectory+"tree_electron_218_1_FgI.root")
mainFiles.append(mainDirectory+"tree_electron_219_1_d5v.root")
mainFiles.append(mainDirectory+"tree_electron_21_1_gel.root")
mainFiles.append(mainDirectory+"tree_electron_220_1_888.root")
mainFiles.append(mainDirectory+"tree_electron_221_1_T4T.root")
mainFiles.append(mainDirectory+"tree_electron_222_1_yQT.root")
mainFiles.append(mainDirectory+"tree_electron_223_1_6xF.root")
mainFiles.append(mainDirectory+"tree_electron_224_1_JFn.root")
mainFiles.append(mainDirectory+"tree_electron_225_1_UkS.root")
mainFiles.append(mainDirectory+"tree_electron_226_1_BTO.root")
mainFiles.append(mainDirectory+"tree_electron_227_1_r5W.root")
mainFiles.append(mainDirectory+"tree_electron_228_1_5HI.root")
mainFiles.append(mainDirectory+"tree_electron_229_1_RTC.root")
mainFiles.append(mainDirectory+"tree_electron_22_1_tFc.root")
mainFiles.append(mainDirectory+"tree_electron_230_1_RBI.root")
mainFiles.append(mainDirectory+"tree_electron_231_1_2nF.root")
mainFiles.append(mainDirectory+"tree_electron_232_1_9fK.root")
mainFiles.append(mainDirectory+"tree_electron_233_1_5x5.root")
mainFiles.append(mainDirectory+"tree_electron_234_1_cqo.root")
mainFiles.append(mainDirectory+"tree_electron_235_1_Odz.root")
mainFiles.append(mainDirectory+"tree_electron_236_1_Zit.root")
mainFiles.append(mainDirectory+"tree_electron_237_1_Ufu.root")
mainFiles.append(mainDirectory+"tree_electron_238_1_cSr.root")
mainFiles.append(mainDirectory+"tree_electron_239_1_vNZ.root")
mainFiles.append(mainDirectory+"tree_electron_23_1_ndg.root")
mainFiles.append(mainDirectory+"tree_electron_240_1_RAS.root")
mainFiles.append(mainDirectory+"tree_electron_241_1_W3x.root")
mainFiles.append(mainDirectory+"tree_electron_242_1_uuW.root")
mainFiles.append(mainDirectory+"tree_electron_243_1_lyQ.root")
mainFiles.append(mainDirectory+"tree_electron_244_1_93O.root")
mainFiles.append(mainDirectory+"tree_electron_245_1_w3E.root")
mainFiles.append(mainDirectory+"tree_electron_246_1_hhd.root")
mainFiles.append(mainDirectory+"tree_electron_247_1_JqT.root")
mainFiles.append(mainDirectory+"tree_electron_248_1_ZT8.root")
mainFiles.append(mainDirectory+"tree_electron_249_1_Nfo.root")
mainFiles.append(mainDirectory+"tree_electron_24_1_5OS.root")
mainFiles.append(mainDirectory+"tree_electron_250_1_Vcn.root")
mainFiles.append(mainDirectory+"tree_electron_251_1_bfj.root")
mainFiles.append(mainDirectory+"tree_electron_252_1_zer.root")
mainFiles.append(mainDirectory+"tree_electron_25_1_hUK.root")
mainFiles.append(mainDirectory+"tree_electron_26_1_wnV.root")
mainFiles.append(mainDirectory+"tree_electron_27_1_VHl.root")
mainFiles.append(mainDirectory+"tree_electron_28_1_YDe.root")
mainFiles.append(mainDirectory+"tree_electron_29_1_O2X.root")
mainFiles.append(mainDirectory+"tree_electron_2_1_Nmw.root")
mainFiles.append(mainDirectory+"tree_electron_30_1_2z5.root")
mainFiles.append(mainDirectory+"tree_electron_31_1_HvV.root")
mainFiles.append(mainDirectory+"tree_electron_32_1_etV.root")
mainFiles.append(mainDirectory+"tree_electron_33_1_BfI.root")
mainFiles.append(mainDirectory+"tree_electron_34_1_e53.root")
mainFiles.append(mainDirectory+"tree_electron_35_1_sLF.root")
mainFiles.append(mainDirectory+"tree_electron_36_1_dic.root")
mainFiles.append(mainDirectory+"tree_electron_37_1_xe0.root")
mainFiles.append(mainDirectory+"tree_electron_38_1_K1F.root")
mainFiles.append(mainDirectory+"tree_electron_39_1_XXK.root")
mainFiles.append(mainDirectory+"tree_electron_3_1_qgC.root")
mainFiles.append(mainDirectory+"tree_electron_40_1_2E1.root")
mainFiles.append(mainDirectory+"tree_electron_41_1_ImZ.root")
mainFiles.append(mainDirectory+"tree_electron_42_1_f7F.root")
mainFiles.append(mainDirectory+"tree_electron_43_1_t8i.root")
mainFiles.append(mainDirectory+"tree_electron_44_1_vax.root")
mainFiles.append(mainDirectory+"tree_electron_45_1_jVi.root")
mainFiles.append(mainDirectory+"tree_electron_46_1_nSX.root")
mainFiles.append(mainDirectory+"tree_electron_47_1_11e.root")
mainFiles.append(mainDirectory+"tree_electron_48_1_vTB.root")
mainFiles.append(mainDirectory+"tree_electron_49_1_Uwk.root")
mainFiles.append(mainDirectory+"tree_electron_4_1_y5c.root")
mainFiles.append(mainDirectory+"tree_electron_50_1_ScU.root")
mainFiles.append(mainDirectory+"tree_electron_51_1_OUW.root")
mainFiles.append(mainDirectory+"tree_electron_52_1_VLa.root")
mainFiles.append(mainDirectory+"tree_electron_53_1_A3S.root")
mainFiles.append(mainDirectory+"tree_electron_54_1_6sA.root")
mainFiles.append(mainDirectory+"tree_electron_55_1_90n.root")
mainFiles.append(mainDirectory+"tree_electron_56_1_c4f.root")
mainFiles.append(mainDirectory+"tree_electron_57_1_W6R.root")
mainFiles.append(mainDirectory+"tree_electron_58_1_pcN.root")
mainFiles.append(mainDirectory+"tree_electron_59_1_rf1.root")
mainFiles.append(mainDirectory+"tree_electron_5_1_86y.root")
mainFiles.append(mainDirectory+"tree_electron_60_1_oo8.root")
mainFiles.append(mainDirectory+"tree_electron_61_1_9rk.root")
mainFiles.append(mainDirectory+"tree_electron_62_1_9hM.root")
mainFiles.append(mainDirectory+"tree_electron_63_1_Sdl.root")
mainFiles.append(mainDirectory+"tree_electron_64_1_H6v.root")
mainFiles.append(mainDirectory+"tree_electron_65_1_A3n.root")
mainFiles.append(mainDirectory+"tree_electron_66_1_vmf.root")
mainFiles.append(mainDirectory+"tree_electron_67_1_jlF.root")
mainFiles.append(mainDirectory+"tree_electron_68_1_1y3.root")
mainFiles.append(mainDirectory+"tree_electron_69_1_CDM.root")
mainFiles.append(mainDirectory+"tree_electron_6_1_kyh.root")
mainFiles.append(mainDirectory+"tree_electron_70_1_SLO.root")
mainFiles.append(mainDirectory+"tree_electron_71_1_mxy.root")
mainFiles.append(mainDirectory+"tree_electron_72_1_zLH.root")
mainFiles.append(mainDirectory+"tree_electron_73_1_k4Q.root")
mainFiles.append(mainDirectory+"tree_electron_74_1_AgG.root")
mainFiles.append(mainDirectory+"tree_electron_75_1_U7T.root")
mainFiles.append(mainDirectory+"tree_electron_76_1_i0z.root")
mainFiles.append(mainDirectory+"tree_electron_77_1_4cY.root")
mainFiles.append(mainDirectory+"tree_electron_78_1_kwD.root")
mainFiles.append(mainDirectory+"tree_electron_79_1_6Zp.root")
mainFiles.append(mainDirectory+"tree_electron_7_1_Tt4.root")
mainFiles.append(mainDirectory+"tree_electron_80_1_tYb.root")
mainFiles.append(mainDirectory+"tree_electron_81_1_H18.root")
mainFiles.append(mainDirectory+"tree_electron_82_1_2jS.root")
mainFiles.append(mainDirectory+"tree_electron_83_1_nYG.root")
mainFiles.append(mainDirectory+"tree_electron_84_1_gMH.root")
mainFiles.append(mainDirectory+"tree_electron_85_1_CjG.root")
mainFiles.append(mainDirectory+"tree_electron_86_1_8JS.root")
mainFiles.append(mainDirectory+"tree_electron_87_1_I6A.root")
mainFiles.append(mainDirectory+"tree_electron_88_1_XTW.root")
mainFiles.append(mainDirectory+"tree_electron_89_1_Mwp.root")
mainFiles.append(mainDirectory+"tree_electron_8_1_sSD.root")
mainFiles.append(mainDirectory+"tree_electron_90_1_QyS.root")
mainFiles.append(mainDirectory+"tree_electron_91_1_Tn5.root")
mainFiles.append(mainDirectory+"tree_electron_92_1_RUo.root")
mainFiles.append(mainDirectory+"tree_electron_93_1_jWl.root")
mainFiles.append(mainDirectory+"tree_electron_94_1_Ulm.root")
mainFiles.append(mainDirectory+"tree_electron_95_1_zUF.root")
mainFiles.append(mainDirectory+"tree_electron_96_1_8FF.root")
mainFiles.append(mainDirectory+"tree_electron_97_1_fmb.root")
mainFiles.append(mainDirectory+"tree_electron_98_1_0FV.root")
mainFiles.append(mainDirectory+"tree_electron_99_1_KQa.root")
mainFiles.append(mainDirectory+"tree_electron_9_1_v8T.root")


treeClass = "EgammaStage1Stage2Trees"

mainTree = Tree()
mainTree.name = "electronNtuplizer/electronTree"
mainTree.files = mainFiles

secondaryTrees = []
secondaryTrees.append(Tree())
secondaryTrees[-1].name = "l1TriggerNtuplizer/l1TriggerTree"
secondaryTrees[-1].files = ["/grid_mnt/data1__data.polcms/cms/sauvan/L1/Ntuples/Stage2Trees/Neutrino_Pt-2to20_gun/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW/2014_09_11/tree_stage2_*.root"]

secondaryTrees.append(Tree())
secondaryTrees[-1].name = "l1TriggerNtuplizer/l1TriggerTree"
secondaryTrees[-1].files = ["/grid_mnt/data1__data.polcms/cms/sauvan/L1/Ntuples/Stage1Trees/Neutrino_Pt-2to20_gun/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW/2014_09_19/tree_stage1_*.root"]

batch = BatchLauncher()
batch.name = "merge_eg_stage1_stage2"
batch.outputDirectory = outputDirectory
batch.outputFile = outputFile
batch.treeClass = treeClass
batch.mainTree = mainTree
batch.secondaryTrees = secondaryTrees
batch.nFilesPerJob = 3
batch.scram_arch = "slc5_amd64_gcc472"
batch.cmsswDir = "/home/llr/cms/sauvan/CMSSW/L1_Emulator/CMSSW_6_2_11/"
